# Generated by Django 5.2.3 on 2025-07-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorysystem',
            old_name='object_id',
            new_name='entity_id',
        ),
        migrations.RemoveField(
            model_name='categorysystem',
            name='content_type',
        ),
        migrations.AddField(
            model_name='categorysystem',
            name='entity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='categorysystem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('entity__isnull', True), ('entity_id__isnull', True)), models.Q(('entity__isnull', False), ('entity_id__isnull', False)), _connector='OR'), name='categorysystem_entity_xor_null'),
        ),
    ]
