# Generated by Django 5.2.3 on 2025-07-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_rename_object_id_categorysystem_entity_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'category_system'), ('slug', 'category_system')},
        ),
        migrations.AlterField(
            model_name='category',
            name='path',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'category_system'), ('path', 'category_system'), ('slug', 'category_system')},
        ),
    ]
