# Generated by Django 5.2.3 on 2025-08-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_options_product_attribute_set_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
