# Generated by Django 5.2.3 on 2025-08-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productattribute_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='sample_values',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
