# Generated by Django 5.2.3 on 2025-08-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('products', '0007_productattribute_sample_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributeset',
            name='product_type_brands',
            field=models.ManyToManyField(related_name='product_attribute_sets', to='brands.brand'),
        ),
    ]
