# Generated by Django 5.2.3 on 2025-08-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productattributeset_product_type_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='display_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
