# Generated by Django 5.2.3 on 2025-10-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productattribute_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('FAILEd', 'Failed Verification')], default='PENDING', help_text="Status realted to AI generated product's that require verification", max_length=25),
        ),
    ]
