# Generated by Django 5.2.3 on 2025-10-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_is_ai_generated_product_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed Verification'), ('EXEMPT', 'Does not require verification')], default='EXEMPT', help_text="Status realted to AI generated product's that require verification", max_length=25),
        ),
    ]
