# Generated by Django 5.2.3 on 2025-10-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='suggested_corrections',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
