# Generated by Django 5.2.3 on 2025-10-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_suggested_corrections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed Verification'), ('EXEMPT', 'Does not require verification'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted')], default='EXEMPT', help_text="Status realted to AI generated product's that require verification", max_length=25),
        ),
    ]
