# Generated by Django 5.2.3 on 2025-10-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributeset',
            name='lookup_field',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
