# Generated by Django 5.2.3 on 2025-11-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productattributeset_lookup_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributeset',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productattributeset',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed Verification'), ('EXEMPT', 'Does not require verification'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted')], default='EXEMPT', help_text="Status realted to AI generated product's that require verification", max_length=25),
        ),
    ]
