# Generated by Django 5.2.3 on 2025-12-12 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_productattributeset_is_ai_generated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMonitorJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('target_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('frequency', models.CharField(default='daily', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('job_id', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(help_text='Associated product', on_delete=django.db.models.deletion.CASCADE, related_name='product_monitor_jobs', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Monitor Job',
                'verbose_name_plural': 'Product Monitor Jobs',
                'unique_together': {('product', 'user_id')},
            },
        ),
    ]
