# Generated by Django 5.2.3 on 2025-12-13 19:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_productmonitorjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmonitorjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmonitorjob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
