# Generated by Django 5.2.3 on 2025-11-21 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0015_productattributeset_is_ai_generated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit identifier.', max_length=100, null=True)),
                ('attributes_data', models.JSONField(blank=True, default=dict, help_text='Attributes data for the inventory item', null=True)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='The quantity of the product in stock')),
                ('reserved', models.PositiveIntegerField(default=0, help_text='Quantity reserved for pending orders to prevent overselling')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, help_text='Quantity level that triggers low stock alerts')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the inventory item is active')),
                ('last_stocktake', models.DateTimeField(blank=True, help_text='Date of last physical inventory count', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='The product this inventory item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='products.product')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'ordering': ['product', 'sku'],
                'unique_together': {('product', 'sku')},
            },
        ),
    ]
