# Generated by Django 5.2.3 on 2025-11-16 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0005_category_is_ai_generated_and_more'),
        ('products', '0015_productattributeset_is_ai_generated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('rule_type', models.CharField(blank=True, max_length=255, null=True)),
                ('rule_config', models.JSONField(blank=True, default=dict, null=True)),
                ('active_from', models.DateTimeField(blank=True, null=True)),
                ('active_to', models.DateTimeField(blank=True, null=True)),
                ('callback_function', models.CharField(blank=True, max_length=255, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Price Rule',
                'verbose_name_plural': 'Price Rules',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('currency_code', models.CharField(blank=True, default='USD', max_length=3, null=True)),
                ('region_code', models.CharField(blank=True, default='USA', max_length=3, null=True)),
                ('price_source', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.product')),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('product_attribute_value', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('flat_amount', 'Flat Amount'), ('percentage', 'Percentage'), ('fixed_price', 'Fixed Price')], default='flat_amount', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_modifiers', to='categories.category')),
                ('product_attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_modifiers', to='products.productattribute')),
                ('product_attribute_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_modifiers', to='products.productattributeset')),
                ('price_rules', models.ManyToManyField(related_name='price_modifiers', to='prices.pricerule')),
            ],
            options={
                'verbose_name': 'Price Modifier',
                'verbose_name_plural': 'Price Modifiers',
                'ordering': ['priority'],
            },
        ),
    ]
