# Generated by Django 5.2.3 on 2025-11-11 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_category_is_ai_generated_and_more'),
        ('prices', '0001_initial'),
        ('products', '0015_productattributeset_is_ai_generated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('type', models.CharField(choices=[('flat_amount', 'Flat Amount'), ('percentage', 'Percentage'), ('fixed_price', 'Fixed Price')], default='flat_amount', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_modifiers', to='categories.category')),
                ('product_attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_modifiers', to='products.productattribute')),
            ],
            options={
                'verbose_name': 'Price Modifier',
                'verbose_name_plural': 'Price Modifiers',
                'ordering': ['priority'],
            },
        ),
    ]
