# Generated by Django 5.2.3 on 2025-11-16 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='price_modifiers',
            field=models.ManyToManyField(blank=True, related_name='prices', to='prices.pricemodifier'),
        ),
    ]
