# Generated by Django 5.2.3 on 2025-11-11 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0003_pricemodifier_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricemodifier',
            old_name='product',
            new_name='product_attribute_set',
        ),
    ]
