# Generated by Django 5.2.3 on 2025-11-12 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0004_rename_product_pricemodifier_product_attribute_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricemodifier',
            name='product_attribute_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
