# Generated by Django 5.2.3 on 2025-11-12 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0005_pricemodifier_product_attribute_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('rule_type', models.CharField(blank=True, max_length=255, null=True)),
                ('rule_config', models.JSONField(blank=True, default=dict, null=True)),
                ('active_from', models.DateTimeField(blank=True, null=True)),
                ('active_to', models.DateTimeField(blank=True, null=True)),
                ('callback_function', models.CharField(blank=True, max_length=255, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Price Rule',
                'verbose_name_plural': 'Price Rules',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='PriceModifierRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_modifier_rules', to='prices.pricemodifier')),
                ('price_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_modifier_rules', to='prices.pricerule')),
            ],
            options={
                'verbose_name': 'Price Modifier Rule',
                'verbose_name_plural': 'Price Modifier Rules',
            },
        ),
    ]
