from product_catalog_app.containers.django_container import DjangoContainer
from product_catalog_app.messaging.constants import PRODUCT_CREATION_TOPIC
from typing import List

container = DjangoContainer.get_instance()

def publish_validation_events(product_ids: List[int]) -> None:
    for product_id in product_ids:
        message_data = {
            "product_id": product_id,
            "type": "create",
            "message": "Product Generated By AI for Verification",
        }
        future = container.pubsub_client.publish(PRODUCT_CREATION_TOPIC, message_data)