from product_catalog_app.containers.django_container import DjangoContainer
from product_catalog_app.messaging.constants import PRODUCT_CREATION_TOPIC
from typing import List

container = DjangoContainer.get_instance()

def publish_validation_events(product_ids: List[int]) -> None:
    """Publishes validation events for a list of product IDs.

    Each product ID in the provided list is used to generate and publish a
    "create" type message to the product creation topic, indicating the product
    was generated by AI and requires verification.

    Args:
        product_ids (List[int]): A list of product IDs to publish validation events for.

    Returns:
        None

    Example:
        publish_validation_events([1, 2, 3])
    """
    for product_id in product_ids:
        message_data = {
            "product_id": product_id,
            "type": "create",
            "message": "Product Generated By AI for Verification",
        }
        future = container.pubsub_client.publish(PRODUCT_CREATION_TOPIC, message_data)