# Generated by Django 5.2.3 on 2025-08-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='url',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
