import React from 'react'
import { Product } from '@/types/product'

interface ProductInfoSectionProps {
	product: Product
}

const ProductInfoSection = ({ product }: ProductInfoSectionProps) => {
	return (
		<div className='space-y-6'>
			<h1 className='text-3xl font-extrabold tracking-tight text-gray-900 sm:text-4xl'>
				{product.name} (# {product.id})
			</h1>
			<div className='flex items-center space-x-4 text-sm font-medium text-gray-500'>
				<span className='py-0.5 px-2 bg-purple-100 text-purple-700 rounded-full'>
					Category: {product.category_name || 'No Category'}
				</span>
				<span className='text-gray-600'>
					Brand:{' '}
					<span className='font-semibold text-gray-800'>
						{product.brand_name || 'No Brand'}
					</span>
				</span>
				<span className='text-gray-600'>
					Product Type:{' '}
					<span className='font-semibold text-gray-800'>
						{product.attribute_set_name}
					</span>
				</span>
			</div>
			<div className='flex items-center space-x-4 text-sm text-gray-700'>
				Generated By AI:
				<span className='font-semibold p-1 text-xs rounded-lg'>
					{product.is_ai_generated ? 'Yes' : 'No'}
				</span>
				Verification Status:
				<span
					className={`font-semibold p-1 text-xs rounded-lg ${['PASS', 'EXEMPT'].includes(product.verification_status) ? 'bg-green-100 text-green-700' : 'bg-yellow-100 text-yellow-700'}`}
				>
					{product.verification_status}
				</span>
				Active Status:
				<span className='font-semibold p-1 text-xs rounded-lg'>
					{product.is_active ? 'Yes' : 'No'}
				</span>
			</div>
			<div className='pt-4 border-t border-gray-200'>
				<h2 className='text-lg font-bold text-gray-800 mb-2'>Description</h2>
				<p className='text-gray-600 leading-relax whitespace-pre-warp'>
					{product.description || 'No Description'}
				</p>
			</div>
		</div>
	)
}

export default ProductInfoSection
